/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Contenedor;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Santiago Martinez Diaz (tago)
 */
public class Asignacion_alumnos extends javax.swing.JInternalFrame {
String BD = "jdbc:mysql://localhost/siu";
    String Usuario = "root";
    String Clave = "kingcobra123DA";
    /**
     * Creates new form Asignacion_alumnos
     */
    public Asignacion_alumnos() {
        initComponents();
        
        cbx_carrera();
        cbx_sede();
        cbx_jornada();
        cbx_seccion();
        cbx_Aula();
        cbx_cursos();
        cbx_alumno();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     public void Tabla() {
        try {

            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);

            PreparedStatement ps = cn.prepareStatement("select * from asignacioncursosalumnos;");
            PreparedStatement ps2 = cn.prepareStatement("select * from asignacioncursosalumnos;");
            //pstt4.setString(1, txt_buscar.getText().trim());

            ResultSet rs = ps.executeQuery();

            ResultSet rss = ps2.executeQuery();

            if (rs.next()) {

                DefaultTableModel modelo = new DefaultTableModel();

                modelo.addColumn("codigo_carrera");
                modelo.addColumn("codigo_sede");
                modelo.addColumn("codigo_jornada");
                modelo.addColumn("codigo_seccion");
                modelo.addColumn("codigo_aula");
                modelo.addColumn("codigo_curso");
                modelo.addColumn("carnet_alumno");

                tbl_asignacion.setModel(modelo);

                String[] dato = new String[7];

                while (rss.next()) {
                    dato[0] = rss.getString(1);
                    dato[1] = rss.getString(2);
                    dato[2] = rss.getString(3);
                    dato[3] = rss.getString(4);
                    dato[4] = rss.getString(5);
                    dato[5] = rss.getString(6);
                    dato[6] = rss.getString(7);

                    modelo.addRow(dato);
                }
            }

        } catch (Exception e) {

        }
    }

    public void cbx_carrera() {
        //Codigo que permite consultar registros en la base de datos
        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select nombre_carrera from carreras");

            ResultSet rs = pst.executeQuery();

            //llenar combobox para el comentaario
            cbx_carrera.addItem("Carrera");

            while (rs.next()) {
                cbx_carrera.addItem(rs.getString("nombre_carrera"));
            }

            rs.close();

        } catch (Exception e) {

        }
    }

    public void cbx_sede() {
        //Codigo que permite consultar registros en la base de datos
        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select nombre_sede from sedes");

            ResultSet rs = pst.executeQuery();

            //llenar combobox para el comentaario
            cbx_sede.addItem("Sede");

            while (rs.next()) {
                cbx_sede.addItem(rs.getString("nombre_sede"));
            }

            rs.close();

        } catch (Exception e) {

        }
    }

    public void cbx_jornada() {
        //Codigo que permite consultar registros en la base de datos
        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select nombre_jornada from jornadas");

            ResultSet rs = pst.executeQuery();

            //llenar combobox para el comentaario
            cbx_jornada.addItem("Jornada");

            while (rs.next()) {
                cbx_jornada.addItem(rs.getString("nombre_jornada"));
            }

            rs.close();

        } catch (Exception e) {

        }
    }

    public void cbx_seccion() {
        //Codigo que permite consultar registros en la base de datos
        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select nombre_seccion from secciones");

            ResultSet rs = pst.executeQuery();

            //llenar combobox para el comentaario
            cbx_seccion.addItem("Secciones");

            while (rs.next()) {
                cbx_seccion.addItem(rs.getString("nombre_seccion"));
            }

            rs.close();

        } catch (Exception e) {

        }
    }

    public void cbx_Aula() {
        //Codigo que permite consultar registros en la base de datos
        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select nombre_aula from aulas");

            ResultSet rs = pst.executeQuery();

            //llenar combobox para el comentaario
            cbx_aula.addItem("Aulas");

            while (rs.next()) {
                cbx_aula.addItem(rs.getString("nombre_aula"));
            }

            rs.close();

        } catch (Exception e) {

        }
    }

    public void cbx_cursos() {
        //Codigo que permite consultar registros en la base de datos
        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select nombre_curso from cursos");

            ResultSet rs = pst.executeQuery();

            //llenar combobox para el comentaario
            cbx_curso.addItem("Cursos");

            while (rs.next()) {
                cbx_curso.addItem(rs.getString("nombre_curso"));
            }

            rs.close();

        } catch (Exception e) {

        }
    }

    public void cbx_alumno() {
        //Codigo que permite consultar registros en la base de datos
        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select nombre_alumno from alumnos");

            ResultSet rs = pst.executeQuery();

            //llenar combobox para el comentaario
            cbx_alumno.addItem("Alumno");

            while (rs.next()) {
                cbx_alumno.addItem(rs.getString("nombre_alumno"));
            }

            rs.close();

        } catch (Exception e) {

        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        añadir = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_asignacion = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cbx_alumno = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbx_curso = new javax.swing.JComboBox<>();
        cbx_aula = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbx_seccion = new javax.swing.JComboBox<>();
        cbx_jornada = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbx_sede = new javax.swing.JComboBox<>();
        cbx_carrera = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lbl_carrera = new javax.swing.JLabel();
        lbl_sede = new javax.swing.JLabel();
        lbl_jornada = new javax.swing.JLabel();
        lbl_seccion = new javax.swing.JLabel();
        lbl_aula = new javax.swing.JLabel();
        lbl_curso = new javax.swing.JLabel();
        lbl_alumno = new javax.swing.JLabel();
        Txt_Buscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setVisible(true);

        añadir.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        añadir.setForeground(new java.awt.Color(0, 0, 153));
        añadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Save-icon.png"))); // NOI18N
        añadir.setText("AÑADIR");
        añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirActionPerformed(evt);
            }
        });

        modificar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        modificar.setForeground(new java.awt.Color(0, 0, 153));
        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/update icon.png"))); // NOI18N
        modificar.setText("MODIFICAR");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        buscar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(0, 0, 153));
        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/xmag_search_find_export_locate_5984.png"))); // NOI18N
        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/erase-128.png"))); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(añadir)))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(buscar)
                        .addGap(64, 64, 64))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(añadir)
                .addGap(19, 19, 19)
                .addComponent(modificar)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(54, 54, 54)
                .addComponent(buscar)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        tbl_asignacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Carrera", "Codigo Sede", "Codigo Jornada", "Codigo Seccion", "Codigo Aula", "Codigo Curso", "Codigo Maestro"
            }
        ));
        tbl_asignacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_asignacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_asignacion);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asignacion Alumnos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(0, 0, 153))); // NOI18N

        cbx_alumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_alumnoMouseClicked(evt);
            }
        });
        cbx_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_alumnoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Carnet Alumno:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Codigo Curso:");

        cbx_curso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_cursoMouseClicked(evt);
            }
        });
        cbx_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_cursoActionPerformed(evt);
            }
        });

        cbx_aula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_aulaMouseClicked(evt);
            }
        });
        cbx_aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_aulaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Codigo Aula:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Codigo Seccion:");

        cbx_seccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_seccionMouseClicked(evt);
            }
        });
        cbx_seccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_seccionActionPerformed(evt);
            }
        });

        cbx_jornada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_jornadaMouseClicked(evt);
            }
        });
        cbx_jornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_jornadaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Codigo Jornada:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Codigo Sede:");

        cbx_sede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_sedeMouseClicked(evt);
            }
        });
        cbx_sede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_sedeActionPerformed(evt);
            }
        });

        cbx_carrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_carreraMouseClicked(evt);
            }
        });
        cbx_carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_carreraActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Codigo Carrera:");

        lbl_carrera.setText("Codigo");

        lbl_sede.setText("Codigo");

        lbl_jornada.setText("Codigo");

        lbl_seccion.setText("Codigo");

        lbl_aula.setText("Codigo");

        lbl_curso.setText("Codigo");

        lbl_alumno.setText("Codigo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(40, 40, 40)
                        .addComponent(cbx_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(58, 58, 58)
                        .addComponent(cbx_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(36, 36, 36)
                        .addComponent(cbx_jornada, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(40, 40, 40)
                        .addComponent(cbx_seccion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(62, 62, 62)
                        .addComponent(cbx_aula, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(51, 51, 51)
                        .addComponent(cbx_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(41, 41, 41)
                        .addComponent(cbx_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_carrera)
                    .addComponent(lbl_sede)
                    .addComponent(lbl_jornada)
                    .addComponent(lbl_seccion)
                    .addComponent(lbl_aula)
                    .addComponent(lbl_curso)
                    .addComponent(lbl_alumno))
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_carrera)
                        .addGap(12, 12, 12)
                        .addComponent(lbl_sede)
                        .addGap(12, 12, 12)
                        .addComponent(lbl_jornada)
                        .addGap(12, 12, 12)
                        .addComponent(lbl_seccion)
                        .addGap(20, 20, 20)
                        .addComponent(lbl_aula)
                        .addGap(23, 23, 23)
                        .addComponent(lbl_curso)
                        .addGap(22, 22, 22)
                        .addComponent(lbl_alumno))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbx_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cbx_sede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel4))
                            .addComponent(cbx_jornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel6))
                            .addComponent(cbx_seccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cbx_aula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(cbx_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(cbx_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/storage_database_databases_data_icon_141907.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirActionPerformed
        //Codigo que permite Ingresar registros en la base de datos
        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("insert into asignacioncursosalumnos values(?,?,?,?,?,?,?)");

            pst.setString(1, lbl_carrera.getText().trim());
            pst.setString(2, lbl_sede.getText().trim());
            pst.setString(3, lbl_jornada.getText().trim());
            pst.setString(4, lbl_seccion.getText().trim());
            pst.setString(5, lbl_aula.getText().trim());
            pst.setString(6, lbl_curso.getText().trim());
            pst.setString(7, lbl_alumno.getText().trim());
           

            pst.executeUpdate();

            cbx_carrera.setSelectedIndex(0);
            cbx_sede.setSelectedIndex(0);
            cbx_jornada.setSelectedIndex(0);
            cbx_seccion.setSelectedIndex(0);
            cbx_aula.setSelectedIndex(0);
            cbx_curso.setSelectedIndex(0);
            cbx_alumno.setSelectedIndex(0);

            lbl_carrera.setText("Codigo");
            lbl_sede.setText("Codigo");
            lbl_jornada.setText("Codigo");
            lbl_seccion.setText("Codigo");
            lbl_aula.setText("Codigo");
            lbl_curso.setText("Codigo");
            lbl_alumno.setText("Codigo");

            JOptionPane.showMessageDialog(this, "¡REGISTRO EXITOSO!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            Tabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "¡Error en registro!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_añadirActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        //Codigo que permite Modificar registros en la base de datos
        try {
            String ID = lbl_carrera.getText().trim();

            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("update asignacioncursosalumnos set codigo_carrera= ?, codigo_sede=?, codigo_jornada=?, codigo_seccion=?, codigo_aula=?, codigo_curso=?, carnet_alumno=? where codigo_carrera = " + ID);

            pst.setString(1, lbl_carrera.getText().trim());
            pst.setString(2, lbl_sede.getText().trim());
            pst.setString(3, lbl_jornada.getText().trim());
            pst.setString(4, lbl_seccion.getText().trim());
            pst.setString(5, lbl_aula.getText().trim());
            pst.setString(6, lbl_curso.getText().trim());
            pst.setString(7, lbl_alumno.getText().trim());

            pst.executeUpdate();

            cbx_carrera.setSelectedIndex(0);
            cbx_sede.setSelectedIndex(0);
            cbx_jornada.setSelectedIndex(0);
            cbx_seccion.setSelectedIndex(0);
            cbx_aula.setSelectedIndex(0);
            cbx_curso.setSelectedIndex(0);
            cbx_alumno.setSelectedIndex(0);

            lbl_carrera.setText("Codigo");
            lbl_sede.setText("Codigo");
            lbl_jornada.setText("Codigo");
            lbl_seccion.setText("Codigo");
            lbl_aula.setText("Codigo");
            lbl_curso.setText("Codigo");
            lbl_alumno.setText("Codigo");

            JOptionPane.showMessageDialog(this, "¡MODIFICACION EXITOSA!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            Tabla();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en modificación", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        //Codigo que permite consultar registros en la base de datos
        try {

            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);

            PreparedStatement pstt4 = cn.prepareStatement("select * from asignacioncursosalumnos where carnet_alumno=?");
            pstt4.setString(1, Txt_Buscar.getText().trim());

            ResultSet rss4 = pstt4.executeQuery();

            // hacer la copia del query para que la tabla empiece desde 1
            PreparedStatement ps = cn.prepareStatement("select * from asignacioncursosalumnos where carnet_alumno=?");
            ps.setString(1, Txt_Buscar.getText().trim());

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {

                DefaultTableModel modelo = new DefaultTableModel();

                modelo.addColumn("codigo_carrera");
                modelo.addColumn("codigo_sede");
                modelo.addColumn("codigo_jornada");
                modelo.addColumn("codigo_seccion");
                modelo.addColumn("codigo_aula");
                modelo.addColumn("codigo_curso");
                modelo.addColumn("carnet_alumno");

                tbl_asignacion.setModel(modelo);

                String[] dato = new String[7];

                while (rss4.next()) {
                    dato[0] = rss4.getString(1);
                    dato[1] = rss4.getString(2);
                    dato[2] = rss4.getString(3);
                    dato[3] = rss4.getString(4);
                    dato[4] = rss4.getString(5);
                    dato[5] = rss4.getString(6);
                    dato[6] = rss4.getString(7);
                    modelo.addRow(dato);

                }
            } else {
                JOptionPane.showMessageDialog(null, "Alumno no Registrado");
            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_buscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Codigo que permite borrar registros en la base de datos
        try {

            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("delete from asignacioncursosalumnos where codigo_carrera = ?");

            pst.setString(1, lbl_carrera.getText().trim());
            pst.executeUpdate();

            cbx_carrera.setSelectedIndex(0);
            cbx_sede.setSelectedIndex(0);
            cbx_jornada.setSelectedIndex(0);
            cbx_seccion.setSelectedIndex(0);
            cbx_aula.setSelectedIndex(0);
            cbx_curso.setSelectedIndex(0);
            cbx_alumno.setSelectedIndex(0);

            lbl_carrera.setText("Codigo");
            lbl_sede.setText("Codigo");
            lbl_jornada.setText("Codigo");
            lbl_seccion.setText("Codigo");
            lbl_aula.setText("Codigo");
            lbl_curso.setText("Codigo");
            lbl_alumno.setText("Codigo");

            JOptionPane.showMessageDialog(this, "¡ELIMINACION EXITOSA!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            Tabla();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en eliminación", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tbl_asignacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_asignacionMouseClicked
        // TODO add your handling code here:
        int seleccionar = tbl_asignacion.rowAtPoint(evt.getPoint());

        /*cbx_carrera.setSelectedItem(valueOf(tbl_asignacion.getValueAt(seleccionar, 0)));
        cbx_sede.setSelectedItem(valueOf(tbl_asignacion.getValueAt(seleccionar, 1)));
        cbx_jornada.setSelectedItem(valueOf(tbl_asignacion.getValueAt(seleccionar, 2)));
        cbx_seccion.setSelectedItem(valueOf(tbl_asignacion.getValueAt(seleccionar, 3)));
        cbx_aula.setSelectedItem(valueOf(tbl_asignacion.getValueAt(seleccionar, 4)));
        cbx_curso.setSelectedItem(valueOf(tbl_asignacion.getValueAt(seleccionar, 5)));
        cbx_maestro.setSelectedItem(valueOf(tbl_asignacion.getValueAt(seleccionar, 6)));*/

        lbl_carrera.setText(String.valueOf(tbl_asignacion.getValueAt(seleccionar, 0)));
        lbl_sede.setText(String.valueOf(tbl_asignacion.getValueAt(seleccionar, 1)));
        lbl_jornada.setText(String.valueOf(tbl_asignacion.getValueAt(seleccionar, 2)));
        lbl_seccion.setText(String.valueOf(tbl_asignacion.getValueAt(seleccionar, 3)));
        lbl_aula.setText(String.valueOf(tbl_asignacion.getValueAt(seleccionar, 4)));
        lbl_curso.setText(String.valueOf(tbl_asignacion.getValueAt(seleccionar, 5)));
        lbl_alumno.setText(String.valueOf(tbl_asignacion.getValueAt(seleccionar, 6)));

        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select nombre_carrera from carreras where codigo_carrera=?;");
            pst.setString(1, lbl_carrera.getText());
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                cbx_carrera.setSelectedItem(rs.getString("nombre_carrera"));
            }
        } catch (Exception e) {
        }

        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select nombre_sede from sedes where codigo_sede=?;");
            pst.setString(1, lbl_sede.getText());
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                cbx_sede.setSelectedItem(rs.getString("nombre_sede"));
            }
        } catch (Exception e) {
        }

        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select nombre_jornada from jornadas where codigo_jornada=?;");
            pst.setString(1, lbl_jornada.getText());
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                cbx_jornada.setSelectedItem(rs.getString("nombre_jornada"));
            }
        } catch (Exception e) {
        }

        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select nombre_seccion from secciones where codigo_seccion=?;");
            pst.setString(1, lbl_seccion.getText());
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                cbx_seccion.setSelectedItem(rs.getString("nombre_seccion"));
            }
        } catch (Exception e) {
        }

        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select nombre_aula from aulas where codigo_aula=?;");
            pst.setString(1, lbl_aula.getText());
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                cbx_aula.setSelectedItem(rs.getString("nombre_aula"));
            }
        } catch (Exception e) {
        }

        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select nombre_curso from cursos where codigo_curso=?;");
            pst.setString(1, lbl_curso.getText());
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                cbx_curso.setSelectedItem(rs.getString("nombre_curso"));
            }
        } catch (Exception e) {
        }

        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select nombre_alumno from alumnos where carnet_alumno=?;");
            pst.setString(1, lbl_alumno.getText());
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                cbx_alumno.setSelectedItem(rs.getString("nombre_alumno"));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tbl_asignacionMouseClicked

    private void cbx_alumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_alumnoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_alumnoMouseClicked

    private void cbx_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_alumnoActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select carnet_alumno from alumnos where nombre_alumno=?");
            pst.setString(1, cbx_alumno.getSelectedItem().toString());

            ResultSet rs = pst.executeQuery();

            //llenar combobox para el comentaario
            //cbx_facultad.addItem("Facultad");
            if (rs.next()) {
                lbl_alumno.setText(rs.getString("carnet_alumno"));
            }

            //rs.close();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_cbx_alumnoActionPerformed

    private void cbx_cursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_cursoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_cursoMouseClicked

    private void cbx_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_cursoActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select codigo_curso from cursos where nombre_curso=?");
            pst.setString(1, cbx_curso.getSelectedItem().toString());

            ResultSet rs = pst.executeQuery();

            //llenar combobox para el comentaario
            //cbx_facultad.addItem("Facultad");
            if (rs.next()) {
                lbl_curso.setText(rs.getString("codigo_curso"));
            }

            //rs.close();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_cbx_cursoActionPerformed

    private void cbx_aulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_aulaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_aulaMouseClicked

    private void cbx_aulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_aulaActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select codigo_aula from aulas where nombre_aula=?");
            pst.setString(1, cbx_aula.getSelectedItem().toString());

            ResultSet rs = pst.executeQuery();

            //llenar combobox para el comentaario
            //cbx_facultad.addItem("Facultad");
            if (rs.next()) {
                lbl_aula.setText(rs.getString("codigo_aula"));
            }

            //rs.close();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_cbx_aulaActionPerformed

    private void cbx_seccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_seccionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_seccionMouseClicked

    private void cbx_seccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_seccionActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select codigo_seccion from secciones where nombre_seccion=?");
            pst.setString(1, cbx_seccion.getSelectedItem().toString());

            ResultSet rs = pst.executeQuery();

            //llenar combobox para el comentaario
            //cbx_facultad.addItem("Facultad");
            if (rs.next()) {
                lbl_seccion.setText(rs.getString("codigo_seccion"));
            }

            //rs.close();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_cbx_seccionActionPerformed

    private void cbx_jornadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_jornadaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_jornadaMouseClicked

    private void cbx_jornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_jornadaActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select codigo_jornada from jornadas where nombre_jornada=?");
            pst.setString(1, cbx_jornada.getSelectedItem().toString());

            ResultSet rs = pst.executeQuery();

            //llenar combobox para el comentaario
            //cbx_facultad.addItem("Facultad");
            if (rs.next()) {
                lbl_jornada.setText(rs.getString("codigo_jornada"));
            }

            //rs.close();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_cbx_jornadaActionPerformed

    private void cbx_sedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_sedeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_sedeMouseClicked

    private void cbx_sedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_sedeActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select codigo_sede from sedes where nombre_sede=?");
            pst.setString(1, cbx_sede.getSelectedItem().toString());

            ResultSet rs = pst.executeQuery();

            //llenar combobox para el comentaario
            //cbx_facultad.addItem("Facultad");
            if (rs.next()) {
                lbl_sede.setText(rs.getString("codigo_sede"));
            }

            //rs.close();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_cbx_sedeActionPerformed

    private void cbx_carreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_carreraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_carreraMouseClicked

    private void cbx_carreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_carreraActionPerformed

        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection(BD, Usuario, Clave);
            PreparedStatement pst = cn.prepareStatement("select codigo_carrera from carreras where nombre_carrera=?");
            pst.setString(1, cbx_carrera.getSelectedItem().toString());

            ResultSet rs = pst.executeQuery();

            //llenar combobox para el comentaario
            //cbx_facultad.addItem("Facultad");
            if (rs.next()) {
                lbl_carrera.setText(rs.getString("codigo_carrera"));
            }

            //rs.close();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_cbx_carreraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Tabla();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txt_Buscar;
    private javax.swing.JButton añadir;
    private javax.swing.JButton buscar;
    private javax.swing.JComboBox<String> cbx_alumno;
    private javax.swing.JComboBox<String> cbx_aula;
    private javax.swing.JComboBox<String> cbx_carrera;
    private javax.swing.JComboBox<String> cbx_curso;
    private javax.swing.JComboBox<String> cbx_jornada;
    private javax.swing.JComboBox<String> cbx_seccion;
    private javax.swing.JComboBox<String> cbx_sede;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_alumno;
    private javax.swing.JLabel lbl_aula;
    private javax.swing.JLabel lbl_carrera;
    private javax.swing.JLabel lbl_curso;
    private javax.swing.JLabel lbl_jornada;
    private javax.swing.JLabel lbl_seccion;
    private javax.swing.JLabel lbl_sede;
    private javax.swing.JButton modificar;
    private javax.swing.JTable tbl_asignacion;
    // End of variables declaration//GEN-END:variables
}
